use myfilms;
CALL AdicionarUtilizador('johndoe', 'johndoe@gmail.com', 'password1', 'Normal', '2001-01-01');
select * from utilizador;
CALL AdicionarSessao(1, '2023-06-01 10:00:00', '2023-06-01 11:30:00', 'Desktop', '192.168.0.1', 1,'jhwebfvwhje');
select* from sessão;
CALL AdicionarTag('primeiro filme sonoro');
select* from tags;
CALL AdicionarQuestão('Qual foi o primeiro filme sonoro lançado mundialmente?', 'Português', '2023-06-01 10:00:00', '2023-06-01 10:00:00');
select* from questao;
CALL AdicionarResposta('O primeiro filme sonoro lançado mundialmente foi "O Cantor de Jazz" (The Jazz Singer).', '2023-06-01 10:30:00', 'Aprovada',(SELECT questão_id FROM Questao WHERE texto = 'Qual foi o primeiro filme sonoro lançado mundialmente?'));
select* from resposta;
CALL AddRespostaTag((SELECT resposta_id FROM Resposta WHERE texto = 'O primeiro filme sonoro lançado mundialmente foi "O Cantor de Jazz" (The Jazz Singer).'),(SELECT tag_id FROM Tags WHERE nome_tag='primeiro filme sonoro' LIMIT 1));
select* from resposta_tags;
CALL AdicionarFeedback(1,'5', 'Ótima resposta!', (SELECT resposta_id FROM Resposta WHERE texto = 'O primeiro filme sonoro lançado mundialmente foi "O Cantor de Jazz" (The Jazz Singer).'));
select* from feedback;
CALL AdicionarPesquisa('Filme', (SELECT resposta_id FROM Resposta WHERE texto = 'O diretor do filme "Parasita" é Bong Joon Ho.'), 2,2);
select* from pesquisa;
CALL AdicionarPremio();
select* from premio;
CALL AdicionarAtor('Tim Robbins', 63, null, 'Alive');
CALL AdicionarAtor('Morgan Freeman', 85, null, 'Alive');
select* from ator;
CALL AdicionarRealizador('Francis Ford Coppola', 83, 'Academy Awards 1973', 'Alive');
select* from realizador;
CALL AdicionarProdutora('Castle Rock Entertainment', 'United States', 'Burbank');
select* from produtora;
CALL AdicionarFilme('The Shawshank Redemption', '02:22:00', 16, null, (SELECT nome_produtora FROM Produtora WHERE nome_produtora='Castle Rock Entertainment'), (SELECT nome_ator FROM Ator WHERE nome_ator='Tim Robbins'), (SELECT nome_ator FROM Ator WHERE nome_ator='Morgan Freeman'), (SELECT nome_realizador FROM Realizador WHERE nome_realizador= 'Frank Darabont'), (SELECT id_categoria FROM F_Categoria WHERE nome_f_categoria= 'Drama'), (SELECT id_subcategoria FROM F_Subcategoria WHERE nome_f_subcategoria= 'Crime'));
select* from filme;
SELECT GetFilmNameById(1);
SELECT  GetUtilizadorCount();
